### ISSUE TITLE
quay-enterprise deploy fail

### ISSUE THREAD

**Issue by vap0rtranz** [dongboyan77/quay-on-openshift#4]
Deploy fails of quay-enterprise in running zz_boot.sh.  I had to force an `oc rollout` for some reason after Step #9 and then got the below error.  https://github.com/dongboyan77/quay-on-openshift#9-deploy-quay.  This is OCP v3.11.43.

```
#oc rollout latest dc/quay-enterprise-app -n quay-enterprise
deploymentconfig.apps.openshift.io/quay-enterprise-app rolled out
#oc logs dc/quay-enterprise-app --follow
...
19:33:50 INFO  [util.migrate.cleanup_old_robots] Found 0 robots to delete
*** Running /etc/my_init.d/zz_boot.sh...
/quay-registry/venv/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
No handlers could be found for logger "util.config.provider.baseprovider"
Traceback (most recent call last):
  File "./boot.py", line 113, in <module>
    main()
  File "./boot.py", line 105, in main
    setup_jwt_proxy()
  File "./boot.py", line 73, in setup_jwt_proxy
    get_audience(), expiration_date=expiration)
  File "/quay-registry/venv/local/lib/python2.7/site-packages/cachetools/func.py", line 71, in wrapper
    v = func(*args, **kwargs)
  File "./boot.py", line 36, in get_audience
    if ':' in hostname:
TypeError: argument of type 'NoneType' is not iterable
*** /etc/my_init.d/zz_boot.sh failed with status 1

*** Killing all processes...
Terminated
```

**Comment by dongboyan77** [comment]
There are something wrong in your config file, maybe typo
`  File "./boot.py", line 36, in get_audience
    if ':' in hostname:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by HenriAW** [comment]
Hi, we're getting the same thing in quay 3.3.1. Were you able to resolve this issue?
